export const APP_STATES = {
	LOADING: 1,
	DATA_LOADED: 2
};

export default {
	SET_ERROR: 'SET_ERROR',
	REMOVE_ERROR: 'REMOVE_ERROR',
	ACTIVATE_VIDEO_PANEL: 'ACTIVATE_VIDEO_PANEL',
	DEACTIVATE_VIDEO_PANEL: 'DEACTIVATE_VIDEO_PANEL',
	RECORD_AUDIO_MESSAGE: 'RECORD_AUDIO_MESSAGE',
	STOP_RECORD_AUDIO_MESSAGE: 'STOP_RECORD_AUDIO_MESSAGE',
	UPDATE_APP_STATE: 'UPDATE_APP_STATE'
};
